brew cask install font-roboto
brew cask install font-roboto-condensed
brew cask install font-roboto-slab
brew cask install font-raleway
brew cask install font-oswald
brew cask install font-open-sans
brew cask install font-open-sans-condensed
brew cask install font-noto-serif
brew cask install font-noto-sans
brew cask install font-maven-pro
