brew install --cask font-roboto
brew install --cask font-roboto-condensed
brew install --cask font-roboto-slab
brew install --cask font-raleway
brew install --cask font-oswald
brew install --cask font-open-sans
brew install --cask font-open-sans-condensed
brew install --cask font-noto-serif
brew install --cask font-noto-sans
brew install --cask font-maven-pro
